name = "laneway-r2-upload"
main = "worker.js"
compatibility_date = "2024-12-01"

[[r2_buckets]]
binding = "RECORDINGS_BUCKET"
bucket_name = "laneway-recordings"

[[d1_databases]]
binding = "laneway_analytics"
database_name = "laneway-analytics"
database_id = "52b91c19-46b7-435d-b48b-07767ee21f8e"
